apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: was
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - name: was
        image: maho/java-apl-1st:0.1
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: was
spec:
  type: NodePort
  selector:
    app: was
  ports:
  - protocol: TCP
    port: 9080
    nodePort: 32080    

